import fetch from 'node-fetch';

let handler = async (m, { conn, command }) => {
    const factosLista = [
        // --- PEGA TUS FACTOS AQUÍ ---
        "*Si te dejó por otro, tranquilo: el puesto de 'el mejor' está vacante, no ocupado.*",
        "*El interés no se ruega; si tienes que pedir atención, ya perdiste.*",
        "*No te enamoraste de ella, te enamoraste de la versión que tú mismo inventaste en tu cabeza.*",
        "*La mujer que de verdad te quiere, te va a exigir tiempo, no dinero.*",
        "*Si tu ex te dice 'ojalá encuentres a alguien como yo', dile que esa es la idea xd.*",
        "*El hombre que no sabe lo que quiere, termina perdiendo a la mujer que sí sabía.*",
        "*Amor no es aguantar mierda; amor es crecer juntos, no aguantar traumas ajenos.*",
        "*Si ella sube fotos para que otros la vean, no es tuya, es del público v:.*",
        "*La lealtad hoy en día es un lujo que la gente barata no se puede permitir.*",
        "*No existe la falta de tiempo, existe la falta de interés. Todos tenemos 24 horas.*",
        "*Un hombre que se respeta prefiere estar solo que ser la segunda opción de alguien.*",
        "*Tu mejor amigo no es el que te acolita las estupideces, es el que te dice 'mano, la estás cagando'.*",
        "*Un hombre sin metas es como un coche sin gasolina: se ve bien pero no va a ningún lado.*",
        "*La mayor fuerza de un hombre no está en sus músculos, sino en su autocontrol.*",
        "*Si ella te escribe cuando está aburrida, tú eres el entretenimiento, no el protagonista.*",
        "*El hombre que es bueno con todas, no es bueno con ninguna.*",
        "*Nunca sacrifiques tu progreso por alguien que no sacrificaría su orgullo por ti.*",
        "*Una mujer que sabe lo que vale, no se queda donde no la valoran.*",
        "*El silencio de una mujer duele más que sus gritos.*",
        "*Cuando una mujer decide irse, ya se fue mentalmente hace tres meses.*",
        "*La intuición femenina no falla, lo que falla es que a veces deciden ignorarla.*",
        "*Una mujer independiente no necesita que le resuelvas la vida, necesita que no le jodas la paz.*",
        "*Si el amor es ciego, ¿por qué la lencería es tan cara? xd.*",
        "*El 'para siempre' hoy en día dura lo que tarda en llegar un mensaje de alguien mejor.*",
        "*Tu mejor amigo se está riendo de ti en el grupo que tú no estás.*",
        "*Nadie es indispensable, hasta que el que te hacía el trabajo se va de vacaciones.*",
        "*La gente que dice 'el dinero no da la felicidad' nunca ha estado pobre y triste al mismo tiempo.*",
        "*Si te dice 'no eres tú, soy yo', es verdad: ella ya encontró a alguien que no eres tú.*",
        "*Tu perro te quiere porque le das comida; si fueras un nugget, ya estarías muerto.*",
        "*Gastar dinero en skins no te hace pro, solo te hace un pobre con estilo.*",
        "*Si juegas con el DPI alto y fallas los tiros, no es el mouse, son tus manos de madera.*",
        "*El lag solo aparece cuando vas ganando o cuando estás por matar al boss.*",
        "*Pasar 10 horas en un juego no es perder el tiempo si te salvó de la realidad por un rato.*",
        "*No existe el 'último nivel', siempre hay un chino que lo pasó más rápido que tú.*",
        "*La mayoría de tus amigos solo están contigo porque les queda de camino.*",
        "*Si hablas mal de los demás conmigo, hablas mal de mí con los demás. Facto.*",
        "*La envidia siempre viene de alguien que te ve de abajo.*",
        "*El 90% de tus problemas se solucionarían si dejaras de pensar tanto y empezaras a hacer.*",
        "*La humildad no es ser pobre, es saber que eres grande sin pisotear a nadie.*",
        "*Si tienes que fingir para encajar, el lugar es el equivocado, no tú.*",
        "*Nadie publica sus fracasos en Instagram, por eso ves que todos 'ganan' menos tú.*",
        "*Un título no te quita lo bruto, solo te lo hace más caro.*",
        "*La paz mental es el nuevo estatus social.*",
        "*Ser 'buena persona' no significa dejar que todos te pasen por encima.*",
        "*A veces no es que te falte suerte, es que te falta disciplina.*",
        "*Tu familia también puede ser tóxica; la sangre no es un pase libre para joderte.*",
        "*El karma no es una venganza, es el reflejo de tus acciones.*",
        "*Si el plan A no funciona, el abecedario tiene 26 letras más.*",
        "*La cama de un hospital te enseña más que una iglesia.*",
        "*No cuentes tus planes, deja que los resultados hablen por ti.*",
        "*El que mucho explica, mucho miente.*",
        "*Aprender a decir 'NO' te va a salvar la vida más veces que un chaleco antibalas.*",
        "*La madurez es darte cuenta de que no todo merece tu reacción.*",
        "*Si te da miedo hacerlo, hazlo con miedo, pero hazlo.*",
        "*Las mejores conversaciones se tienen después de las 2 de la mañana.*",
        "*El éxito sin felicidad es el fracaso más grande.*",
        "*La vida no es justa, pero eso no significa que tengas que ser un hdp.*",
        "*Si no trabajas por tus sueños, alguien te va a contratar para que trabajes por los suyos.*",
        "*A veces ganar es perder a esa persona.*",
        "*El orgullo te puede hacer sentir fuerte, pero te deja solo.*",
        "*No busques a alguien que te complete, busca a alguien que te acepte completo.*",
        "*El pasado es un buen lugar para visitar, pero un mal lugar para quedarse.*",
        "*Tener la razón no sirve de nada si pierdes la paz.*",
        "*Los errores son los mejores maestros, siempre y cuando aprendas la lección.*",
        "*La gente nota el cambio en tu actitud, pero nunca nota el comportamiento que causó el cambio.*",
        "*Si te juntas con 5 millonarios, tú serás el sexto. Si te juntas con 5 vagos, también.*",
        "*El tiempo que disfrutas perdiendo no es tiempo perdido.*",
        "*No confundas tener un título con tener educación.*",
        "*El cementerio está lleno de gente que se creía indispensable.*",
        "*La verdadera libertad es no tener que impresionar a nadie.*",
        "*A veces tienes que ser tu propio héroe porque todos los demás están ocupados.*",
        "*La soledad te enseña que no necesitas a cualquiera a tu lado.*",
        "*Si te enfococas en el problema, tendrás más problemas. Si te enfocas en la solución, tendrás opciones.*",
        "*Nadie va a venir a salvarte, la caballería eres tú mismo.*",
        "*El silencio es la mejor respuesta para un necio.*",
        "*No eres lo que logras, eres lo que superas.*",
        "*Gastar energía en odiar a alguien es darle alojamiento gratis en tu cabeza.*",
        "*La vida es corta, pero es lo más largo que vas a hacer en tu vida.*",
        "*No esperes a que sea lunes para empezar algo nuevo.*",
        "*La autodisciplina es la forma más pura de amor propio.*",
        "*El mundo no te debe nada, deja de esperar que las cosas caigan del cielo.*",
        "*Un 'te extraño' no significa nada si el comportamiento sigue siendo el mismo.*",
        "*El respeto se gana, la honestidad se aprecia y la lealtad se devuelve.*",
        "*No puedes sanar en el mismo lugar donde te enfermaste.*",
        "*La opinión de los demás sobre ti no tiene que convertirse en tu realidad.*",
        "*El miedo al 'qué dirán' ha matado más sueños que cualquier fracaso.*",
        "*A veces la puerta que se cierra es para protegerte, no para castigarte.*",
        "*No le des perlas a los cerdos ni tu tiempo a gente que no sabe qué hacer con él.*",
        "*La inteligencia te ayuda a salir de problemas, la sabiduría te ayuda a no entrar en ellos.*",
        "*Si no inviertes en ti, ¿quién lo va a hacer?.*",
        "*La gratitud cambia lo que tenemos en suficiente.*",
        "*Nadie sabe lo que tiene hasta que lo pierde... y lo ve con otro xd.*",
        "*La vida te va a repetir la lección hasta que la aprendas.*",
        "*No te compares con los demás, compárate con quien eras ayer.*",
        "*El éxito es 1% talento y 99% no rendirse como un pendejo.*",
        "*Si no te gusta donde estás, muévete, no eres un árbol.*",
        "*Las personas más difíciles de amar son las que más lo necesitan.*",
        "*Acepta lo que es, suelta lo que fue y ten fe en lo que será.*",
        "*El que sabe callar sabe escuchar, y el que sabe escuchar sabe aprender.*",
        "*Vive de tal manera que si alguien habla mal de ti, nadie le crea.*",
        "*Al final del día, solo te tienes a ti mismo, así que más vale que te lleves bien contigo.*"
        // --- FIN DE LA LISTA ---
    ];

    const factoSujeto = factosLista[Math.floor(Math.random() * factosLista.length)];
    
    const mensajeFinal = `🗿 *FACTO SELECCIONADO* 🗿\n\n${factoSujeto}\n\n_– `;

    // Usamos m.chat y m.sender para que sea compatible con el sistema de plugins
    await conn.sendMessage(m.chat, { text: mensajeFinal, mentions: [m.sender] }, { quoted: m });
};

handler.help = ['facto'];
handler.tags = ['anime'];
handler.command = ['facto', 'factos'];

export default handler